version: "3"

services:
  api-todo:
    build:
      context: ./api-todo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URI=mongodb://mongo:MongoPass@mongodb:27017/
      - DATABASE_USE_MONGODB=true
      - NODE_ENV=development
    networks:
      - api-db-network

  # client-todo:
  #   build:
  #     context: ./client-todo
  #   environment:
  #     - VITE_USE_LOCAL_API="true"
  #     - VITE_API_URL=http://localhost:3000
  #   ports:
  #     - "3005:3005"
  #   depends_on:
  #     - api-todo

  mongodb:
    image: mongo:5.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=MongoPass
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data/db
    networks:
      - api-db-network

  # test-api-todo:
  #   build:
  #     context: ./api-todo-test
  #   environment:
  #     - API_TODO_ENDPOINT=http://localhost:3000
  #   volumes:
  #     - ./api-todo-test:/app
  #   depends_on:
  #     - api-todo
  #     - mongodb

volumes:
  mongodata:

networks:
  api-db-network: