name: API Build/Test

on:
  workflow_dispatch:
  push:
    branches: 
      - '*'
    paths:
      - 'api/**'
  pull_request:
    branches: 
      - 'main'
    paths:
      - 'api-todo/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d mongodb

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: API-todo version
        run: |
          sudo apt-get install jq
          cat api-todo/package.json | jq .version

      - name: Build and run tests
        run: |
          cd api-todo
          npm ci
          npm run lint
          npm run test
        env: # Add your environment variables here
          DATABASE_URI: mongodb://mongo:MongoPass@localhost:27017/
          DATABASE_USE_MONGODB: true

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down