name: Client

on:
  workflow_dispatch:
  push:
    branches: 
      - '*'
    paths:
      - 'client/**'
  pull_request:
    branches: 
      - 'main'
    paths:
      - 'client/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Client-Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Client-Client version
        run: |
          sudo apt-get install jq
          cat client/package.json | jq .version

      - name: Client-Build and run tests
        run: |
          npm ci --workspace=client
          npm run lint --workspace=client
          npm run build --workspace=client
          npm run test --workspace=client
