name: Client Build/Test

on:
  workflow_dispatch:
  push:
    branches: 
      - '*'
    paths:
      - 'client-todo/**'
  pull_request:
    branches: 
      - 'main'
    paths:
      - 'client-todo/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Client-todo version
        run: |
          sudo apt-get install jq
          cat client-todo/package.json | jq .version

      - name: Build and run tests
        run: |
          npm ci --workspace=client-todo
          npm run lint --workspace=client-todo
          npm run build --workspace=client-todo
          npm run test --workspace=client-todo
