name: devx

# Verify local developer experience works
# Docker compose is used to start the various services

on:
    workflow_dispatch:
    push:
      branches: 
        - '*'
    pull_request:
      branches: 
        - '*'
jobs:
    devx-api:
  
      runs-on: ubuntu-latest
  
      strategy:
        matrix:
          node-version: [18.x]
  
      steps:
  
        # Start environment
        - uses: actions/checkout@v2
  
        - name: DEVX-Start database and api
          run: |
            docker compose -f "docker-compose.yml" up -d --build api mongodb
  
        - name: DEVX-Network
          run: |
            docker network ls

        # Wait for MongoDB service to be ready
        - name: Wait for MongoDB service
          run: |
            until docker exec -it mongodb mongo --eval "db.adminCommand('ping')"; do
              echo 'Waiting for MongoDB service...'
              sleep 5
            done

        # Wait for API service to be ready
        - name: Wait for API service
          run: |
            until curl -sf http://localhost:3000; do
              echo 'Waiting for API service...'
              sleep 5
            done

        # verify result is in 200 range
        - name: DEVX-cURL to Root
          run: |
            curl http://localhost:3000/ --verbose

          # verify result is in 200 range
        - name: DEVX-cURL to API
          run: |
            curl http://localhost:3000/todos --verbose
  
        # Stop environment
        - name: DEVX-Stop containers
          if: always()
          run: docker-compose -f "docker-compose.yml" down